version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    
sphinx:
  fail_on_warning: false

python:
  # Install our python package before building the docs
  install:
    - method: pip
      extra_requirements:
        - myst-parser
        - sphinx-autoapi 

formats:
  - pdf
  - epub
