version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    
sphinx:
  fail_on_warning: false
  configuration: docs/conf.py


python:
  # Install our python package before building the docs
  install:
    - requirements: docs/doc_requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - epub
