name: straindesign
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scipy
  - matplotlib-base
  - psutil
  - numpy
  - pandas
  - optlang
  - swiglpk
  - pyscipopt
  - conda-forge::cobra
