{% set version = '1.18' %}

package:
  name: straindesign
  version: {{ version }}

source:
  path: ..
  # git_url: https://github.com/klamt-lab/straindesign
  # git_rev: v{{ version }}

requirements:
  build:
    - python
    - pip
    - setuptools >=64
    - wheel
  run:
    - python
    - scipy
    - matplotlib
    - psutil
    - conda-forge:cobra

build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script:
    - pip install . --no-deps --no-build-isolation

test:
  imports:
    - straindesign

about:
  home:  https://github.com/klamt-lab/straindesign
  license: Apache 2
  license_family: MIT
  license_file: LICENSE
  summary: Computational strain design package for the COBRApy framework.
  doc_url: https://github.com/klamt-lab/straindesign
  dev_url: https://github.com/klamt-lab/straindesign

