{% set version = '0.0.5' %}

package:
  name: optlang_enumerator
  version: {{ version }}

source:
  git_url: https://github.com/cnapy-org/optlang_enumerator.git
  git_rev: v{{ version }}

requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - numpy
    - scipy
    - optlang
    - cobra
    - efmtool_link


build:
  noarch: python
  number: 0  # NOTE: increment for new build/set to zero for new version
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - optlang_enumerator

about:
  home:  https://github.com/cnapy-org/optlang_enumerator
  license: Apache 2
  license_family: MIT
  license_file: LICENSE
  summary: Enumeration of multiple solutions to a MILP with the optlang framework.
  doc_url: https://github.com/cnapy-org/optlang_enumerator
  dev_url: https://github.com/cnapy-org/optlang_enumerator
